### PR TITLE
Add fixy formatters from ZP

### PR DESCRIPTION
**Pull request by juleea**

### CODE REVIEW

**Comment by juleea** [comment]
@Wildebeest looks like i don't have permissions to add a repo in solano. will you give me permission or do that?

**Comment by juleea** [comment]
this repo is public, but i'm planning to push this to our private gem repo

**Comment by Wildebeest** [comment]
Looks awesome. @zp-alfred accept!

**Comment by zp-alfred** [comment]
Accepted by Wildebeest!

**Pull request closed without merging**
